MDFloatLayout
    MDLabel:
        id: task_label
        halign: "center"
        markup: True
        text: "[b][u][size=48]To Do[/size][/u][/b]"
        pos_hint: {"y": .45}
    
    ScrollView:
        pos_hint: {"center_y": .5, "center_x": .5}
        size_hint: .9, .8
        MDList:
            id: container

    MDFloatingActionButton:
        icon: "plus-thick"
        elevation_normal: 12
        pos_hint: {"x" : .45 , "y": .04 }
        
